### ISSUE TITLE
Does not seem to work on hassbian + xorg + openbox

### ISSUE THREAD

**Issue by orcinus** [zpfvo/clicklock#2]
Running this on a hassbian (home assistant + raspian) setup with openbox, on a raspberry pi with the official 7" touch screen display. I'm using openbox to run chromium in kiosk mode, displaying a hadashboard panel for home automation controls (pretty much the setup this was built for, if i'm not mistaken).

For some reason, it's not doing what it's supposed to.

I'm running it (`xssstart clicklock &`) from openbox' autostart. Sometimes it just behaves as it does without clicklock (i.e. first tap also taps blindly on hadashboard widgets). Sometimes the first tap does nothing, i.e. the display stays blanked, and the second tap wakes the screen and again taps on a random widget underneath.

Any ideas on what's going on?

**Comment by zpfvo** [comment]
can you try to find out if xssstart is working as expected? Does it get all the events it needs to?

**Comment by orcinus** [comment]
Captured the output into a log and i think i found the reason...
If OOM protection fails, it actually kills clicklock (which is behaviour inherited from slock), instead of just throwing a warning.

```
if (fd < 0 || write(fd, value, length) != length || close(fd) != 0)
	die("cannot disable the out-of-memory killer for this process (make sure to suid or sgid clicklock)\n");
```

Going to try with u+s now.

**Comment by orcinus** [comment]
That was it!
Works perfectly now.

I don't really think that check is needed. Or, indeed, the OOM protection.
The only reason slock had it was because you don't want your lock screen dying unexpectedly while your machine is unattended (thus exposing your desktop to anyone who walks by).

Since clicklock isn't really a lock screen, there's no real need for all of that.

**Comment by zpfvo** [comment]
Hi thank you very much! I think one could remove the whole `dontkillme(void)` function.
